import type { Room, Experience, DiningVenue, Amenity, Review, Booking, ResortConfig } from './types';

export const SEED_CONFIG: ResortConfig = {
  name: 'KAIROS RESORT',
  subtitle: 'A PRIVATE RESORT BUILT AROUND STILLNESS',
  location: 'Rewari, Haryana • India',
  nearestAirport: 'Indira Gandhi International Airport (DEL)',
  transferTimeAirport: '45 min private transfer',
  transferTimeCity: '30 min from Cyber City',
  taxRate: 0.18, // 18% luxury hospitality GST
  currency: 'INR',
  currencySymbol: '₹',
  contactEmail: 'stay@kairos-resort.com',
  contactPhone: '+91 (0) 124 480 9000',
  conciergePhone: '+91 (0) 124 480 9001',
  address: 'Kairos Sanctuary Corridor, Sector 28, Rewari Greens, Haryana 123401, India',
};

export const SEED_ROOMS: Room[] = [
  {
    id: 'garden-suite',
    name: 'Garden Suite',
    slug: 'garden-suite',
    tagline: 'Quiet ground sanctuary wrapped in native greenery and morning mist',
    description: 'The Garden Suite is an intimate sanctuary designed for rest and quiet contemplation. Natural stone walls, wide sliding glass panels, and a secluded private sun loggia bring the outdoors directly into your living space. Hand-crafted teak joinery, Belgian linen bedding, and a sunken stone rain shower complete the retreat.',
    shortDescription: '72 m² secluded sanctuary with private garden terrace and rain shower.',
    pricePerNight: 28000,
    capacity: 2,
    size: '72 m²',
    bedType: 'King Bed',
    featured: true,
    available: true,
    view: 'Private Zen Garden & Forest Canopy',
    images: [
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?q=80&w=2000&auto=format&fit=crop',
    ],
    amenities: [
      'Private terrace with daybed',
      'Sunken travertine rain shower',
      'Signature artisanal breakfast included',
      'Acoustically isolated glass walls',
      'Bespoke botanical bath amenities',
      'High-speed fiber Wi-Fi',
      'In-suite espresso & tea bar',
      '24/7 dedicated room concierge',
    ],
    highlights: [
      'Direct stepping stone access to the private botanical walk',
      'Floor-to-ceiling motorized acoustic louvers',
      'Custom mattress crafted with natural organic latex',
      'Integrated soft ambient circadian lighting system',
    ],
  },
  {
    id: 'ocean-villa',
    name: 'Horizon Ocean Villa',
    slug: 'horizon-ocean-villa',
    tagline: 'Elevated cantilevered villa with heated plunge pool and expansive views',
    description: 'Hovering effortlessly above the landscaped water basins, the Horizon Ocean Villa features an expansive private cantilevered deck with an infinity heated plunge pool. Uninterrupted glass facades invite natural light throughout the day, transitioning into golden evening twilight across the horizon.',
    shortDescription: '120 m² architectural villa with private heated plunge pool and horizon panorama.',
    pricePerNight: 45000,
    capacity: 3,
    size: '120 m²',
    bedType: 'King Bed + Daybed',
    featured: true,
    available: true,
    view: 'Reflecting Water Basins & Horizon',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1618773928121-c32242e63f39?q=80&w=2000&auto=format&fit=crop',
    ],
    amenities: [
      'Private temperature-controlled plunge pool',
      'Expansive outdoor deck with sun loungers',
      'Freestanding monolithic stone soaking tub',
      'Dual vanity dressing suite',
      'Champagne arrival welcome ritual',
      'Chef-curated gourmet breakfast',
      'Butler on-call service',
      'Sonos architectural sound system',
    ],
    highlights: [
      'Cantilevered water terrace extending 4 meters over the basin',
      'Full marble bathroom with floor-to-ceiling glass wall',
      'Private outdoor rain shower under the open sky',
      'Nightly turn-down aromatherapy and pillow menu',
    ],
  },
  {
    id: 'courtyard-residence',
    name: 'Courtyard Residence',
    slug: 'courtyard-residence',
    tagline: 'Expansive private compound built around a tranquil water reflecting courtyard',
    description: 'The Courtyard Residence offers an architectural experience inspired by traditional courtyard living. Organized around a central tranquil reflecting pool and open-air fireplace, this residence offers two master suites, a formal dining salon, and a private pantry for tailored in-residence culinary service.',
    shortDescription: '180 m² dual-suite compound centered around an open-air water courtyard.',
    pricePerNight: 62000,
    capacity: 4,
    size: '180 m²',
    bedType: '2 Grand King Beds',
    featured: true,
    available: true,
    view: 'Central Private Courtyard & Zen Pond',
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=2000&auto=format&fit=crop',
    ],
    amenities: [
      'Private open-air water courtyard with fireplace',
      'Two master suites with independent ensuite baths',
      'Dedicated dining room for 6 guests',
      'Private butler & dedicated host',
      'Private chef dining option in-residence',
      'Complimentary airport luxury chauffeured transfer',
      'Custom wine cellar collection',
      'Unpacking & packing luggage concierge',
    ],
    highlights: [
      'Enclosed architectural compound ensuring total seclusion',
      'Outdoor sunken seating lounge surrounding water feature',
      'Walk-in Italian dressing rooms for both suites',
      'Direct private access to resort spa pavilion',
    ],
  },
  {
    id: 'horizon-villa',
    name: 'The Horizon Sky Villa',
    slug: 'horizon-sky-villa',
    tagline: 'Dramatic upper-level residence framing endless sky and forest canopies',
    description: 'Perched in the resort’s upper architectural tiers, The Horizon Sky Villa is an emblem of spatial lightness and horizon views. Featuring 16-foot ceiling heights, hand-honed travertine surfaces, and a double-width balcony designed for sunset viewing and private alfresco dinners.',
    shortDescription: '240 m² upper architectural sanctuary with 180° panoramic sky deck.',
    pricePerNight: 78000,
    capacity: 4,
    size: '240 m²',
    bedType: '2 King Beds',
    featured: false,
    available: true,
    view: '180° Panoramic Skyline & Nature Canopy',
    images: [
      'https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1590490360182-c33d57733427?q=80&w=2000&auto=format&fit=crop',
    ],
    amenities: [
      'Wrap-around 180-degree sunset observation deck',
      'Floor-to-ceiling motorized acoustic glass facade',
      'Calacatta marble bathroom with panoramic soaking tub',
      'Private dining salon with wine station',
      'Luxury private airport roundtrip transfers',
      'Priority reservations across all dining venues',
      'Custom in-room wellness and yoga equipment',
      'Dedicated 24-hour estate manager',
    ],
    highlights: [
      'Unrivaled elevation capturing both sunrise and twilight',
      'Custom bronze fireplaces in living and master bedroom',
      'Integrated Bang & Olufsen acoustic system',
      'Private sommelier wine tasting session included per stay',
    ],
  },
  {
    id: 'signature-pavilion',
    name: 'Signature Kairos Pavilion',
    slug: 'signature-kairos-pavilion',
    tagline: 'The pinnacle of resort luxury — an entire private wing with 360-degree views',
    description: 'The architectural centerpiece of Kairos Resort. The Signature Pavilion spans over 420 m² of private living space, featuring three master bedrooms, a private 15-meter heated swimming pool, an expansive entertaining loggia, dedicated spa treatment room, and a team of private chefs and butlers assigned exclusively to your stay.',
    shortDescription: '420 m² master residence featuring private 15m pool, 3 grand suites, and private staff.',
    pricePerNight: 115000,
    capacity: 6,
    size: '420 m²',
    bedType: '3 Grand Master King Suites',
    featured: true,
    available: true,
    view: '360° Uninterrupted Panorama of Kairos Grounds',
    images: [
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?q=80&w=2000&auto=format&fit=crop',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop',
    ],
    amenities: [
      'Private 15m heated infinity swimming pool',
      'Full private culinary brigade and dedicated butler team',
      'In-pavilion private wellness & couples massage room',
      'Private subterranean wine cellar and tasting lounge',
      'Helipad arrival transfer coordination',
      'Customized itinerary with private resort excursions',
      'Unlimited champagne, artisanal pantry & vintage cellar',
      'Direct private entry and underground secure parking',
    ],
    highlights: [
      'The definitive architectural crown of the Kairos estate',
      'Triple-height 22ft living hall with motorized vanishing glass',
      'Hand-carved solid marble bathtubs in all three suites',
      'Private evening fire pit pavilion for stargazing',
    ],
  },
];

export const SEED_EXPERIENCES: Experience[] = [
  {
    id: 'exp-sunrise-breakfast',
    title: 'Private Sunrise Breakfast',
    slug: 'private-sunrise-breakfast',
    category: 'Culinary',
    description: 'An unhurried morning table set amidst the misty dew of our organic orchards. Enjoy freshly baked heritage grains, warm orchard honey, pressed botanical juices, and estate-roasted coffee as the day’s first light illuminates the architecture.',
    duration: '2 Hours',
    price: 4500,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1200&auto=format&fit=crop',
    availability: 'Daily at 06:00 AM',
    highlights: ['Orchard setting', 'Chef-prepared fresh menu', 'Estate botanical infusion bar'],
    capacity: '2 - 6 Guests',
  },
  {
    id: 'exp-nature-walk',
    title: 'Guided Sanctuary Forest Walk',
    slug: 'guided-forest-walk',
    category: 'Nature',
    description: 'Explore the 45-acre protected bio-reserve surrounding Kairos with our resident botanist. Discover indigenous flora, serene shaded streams, birdwatching points, and the natural terrain that inspired the resort’s monolithic design.',
    duration: '2.5 Hours',
    price: 2800,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1448375240586-882707db888b?q=80&w=1200&auto=format&fit=crop',
    availability: 'Morning & Late Afternoon',
    highlights: ['Resident naturalist guide', 'Birdwatching optics provided', 'Herbal tonic refreshment'],
    capacity: 'Up to 8 Guests',
  },
  {
    id: 'exp-sunset-boat',
    title: 'Sunset Water Excursion',
    slug: 'sunset-water-excursion',
    category: 'Adventure',
    description: 'Drift along the peaceful calm of the Kairos waterway basin on a handcrafted wooden solar electric launch. Savor artisanal charcuterie and rare vintage wines while witnessing the sun dip behind the stone architectural silhouette.',
    duration: '2 Hours',
    price: 6500,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop',
    availability: 'Daily at 05:15 PM',
    highlights: ['Silent electric boat', 'Sommelier wine pairing', 'Golden hour photo vantage'],
    capacity: '2 - 4 Guests',
  },
  {
    id: 'exp-ayurvedic-spa',
    title: 'Ayurvedic Longevity & Herbal Ritual',
    slug: 'ayurvedic-longevity-ritual',
    category: 'Wellness',
    description: 'Rebalance mind and body at the Kairos Spa Pavilion. A curated three-hour ritual combining traditional Abhyanga herbal oil massage, warm stone therapy, cedarwood sauna steam, and sound resonance therapy.',
    duration: '3 Hours',
    price: 8500,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?q=80&w=1200&auto=format&fit=crop',
    availability: 'Daily 09:00 AM - 08:00 PM',
    highlights: ['Certified Ayurvedic masters', 'Cold-pressed organic oils', 'Private mineral soak'],
    capacity: 'Individual or Couples',
  },
  {
    id: 'exp-stargazing',
    title: 'Architectural Stargazing & Wine',
    slug: 'architectural-stargazing',
    category: 'Culture',
    description: 'Ascend to the rooftop observatory pavilion under unpolluted night skies. Peer through high-powered astronomical telescopes guided by our astronomer while savoring dark chocolate infusions and aged single malts.',
    duration: '2 Hours',
    price: 5200,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?q=80&w=1200&auto=format&fit=crop',
    availability: 'Evenings at 08:30 PM (Weather permitting)',
    highlights: ['Refractor telescope observation', 'Dark sky certified', 'Rare spirit tasting'],
    capacity: 'Up to 10 Guests',
  },
  {
    id: 'exp-private-pavilion-dining',
    title: 'Private Pavilion Dining',
    slug: 'private-pavilion-dining',
    category: 'Culinary',
    description: 'A bespoke 7-course tasting menu curated exclusively for you by Executive Chef Antoine Sharma, served in a secluded floating architectural pavilion surrounded by candlelit reflection pools.',
    duration: '3 Hours',
    price: 12000,
    priceUnit: 'for two guests',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
    availability: 'Nightly reservations',
    highlights: ['Personal chef & butler', 'Customized menu tailored to preferences', 'Live acoustic cello accompaniment'],
    capacity: '2 - 6 Guests',
  },
  {
    id: 'exp-lake-kayaking',
    title: 'Stillwater Lake Kayaking',
    slug: 'stillwater-lake-kayaking',
    category: 'Adventure',
    description: 'Glide across the mirror-like waters of the resort’s private lake in cedar-strip kayaks. A peaceful early morning or sunset exercise surrounded by whispering bamboo groves and water lilies.',
    duration: '1.5 Hours',
    price: 3000,
    priceUnit: 'per kayak',
    image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?q=80&w=1200&auto=format&fit=crop',
    availability: 'Sunrise & Sunset',
    highlights: ['Handmade wooden kayaks', 'Safety instructor on stand-by', 'Chilled botanical waters'],
    capacity: 'Single or Tandem',
  },
  {
    id: 'exp-yoga-sound',
    title: 'Open-Air Yoga & Sound Meditation',
    slug: 'open-air-yoga-sound',
    category: 'Wellness',
    description: 'Begin your morning with gentle Hatha alignment and Tibetan singing bowl resonance on our open teak pavilion. Breathe the clean forest air and align with the quiet rhythm of the estate.',
    duration: '1.5 Hours',
    price: 2500,
    priceUnit: 'per guest',
    image: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?q=80&w=1200&auto=format&fit=crop',
    availability: 'Daily at 07:00 AM & 06:00 PM',
    highlights: ['Master yoga practitioners', 'Hand-hammered brass singing bowls', 'Organic herbal teas'],
    capacity: 'Up to 12 Guests',
  },
];

export const SEED_DINING: DiningVenue[] = [
  {
    id: 'dining-the-terrace',
    name: 'THE TERRACE',
    slug: 'the-terrace',
    tagline: 'Contemporary seasonal cuisine overlooking the reflecting landscape',
    description: 'Perched over the central water pavilion, The Terrace celebrates micro-seasonal ingredients sourced directly from our on-site organic farm and sustainable regional artisans. Clean culinary technique meets honest flavors in an open-air architectural setting that blurs indoor and outdoor boundaries.',
    cuisine: 'Contemporary Farm-to-Table & Modern Indian',
    hours: 'Breakfast: 07:00 – 11:00 | Lunch: 12:30 – 15:30 | Dinner: 19:00 – 23:00',
    dressCode: 'Resort Elegant',
    ambiance: 'Floating teak terrace with soft ambient candlelight and panoramic horizon views',
    image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=1600&auto=format&fit=crop',
    featuredDishes: [
      { name: 'Charred Rewari Mustard Greens & Ricotta', description: 'Wood-fired sourdough, cold-pressed mustard oil, fermented chili honey', price: '₹1,450' },
      { name: 'Slow-Smoked Himalayan Trout', description: 'Wild sorrel broth, fennel pollen, crispy lotus crisp', price: '₹2,600' },
      { name: 'Aged Travertine Lamb Loin', description: 'Braised shallots, smoked bone marrow emulsion, cardamom jus', price: '₹3,200' },
      { name: 'Wild Saffron & Goat Milk Gelato', description: 'Pistachio praline, crispy honeycomb, rose petal crisp', price: '₹950' },
    ],
  },
  {
    id: 'dining-the-courtyard',
    name: 'THE COURTYARD',
    slug: 'the-courtyard',
    tagline: 'Slow breakfasts, afternoon tea and intimate candlelit dinners',
    description: 'Set within an intimate sheltered stone loggia around an ancient banyan and reflecting pond, The Courtyard offers a peaceful sanctuary for conversation and unhurried dining. Experience curated tea tastings, European patisserie, and refined comfort fare prepared over slow charcoal embers.',
    cuisine: 'Heritage Artisanal Bistro & Specialty Teas',
    hours: 'All-Day Dining: 08:00 – 22:30 | High Tea: 15:30 – 18:00',
    dressCode: 'Smart Casual',
    ambiance: 'Travertine stone cloister with soothing water fountain acoustics',
    image: 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?q=80&w=1600&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop',
    featuredDishes: [
      { name: 'Single-Estate Darjeeling First Flush Service', description: 'Accompanied by warm lavender scones, clotted jersey cream, and house fig preserves', price: '₹1,800' },
      { name: 'Truffled Wild Mushroom Tart', description: 'Puff pastry, aged Gruyère, fresh thyme from the resort greenhouse', price: '₹1,650' },
      { name: 'Ember-Roasted Sweet Onion Soup', description: 'Sourdough crouton, molten alpine cheese, herb oil', price: '₹1,150' },
      { name: 'Handmade Saffron Pappardelle', description: 'Morel mushrooms, brown butter emulsion, toasted pine kernels', price: '₹2,400' },
    ],
  },
  {
    id: 'dining-private-dining',
    name: 'PRIVATE DINING',
    slug: 'private-dining',
    tagline: 'Personalized dining experiences in secluded architectural sanctuaries',
    description: 'For celebratory occasions or moments requiring absolute seclusion, our culinary team designs completely bespoke menus served in your choice of private setting: the secret orchard clearing, the subterranean wine cellar, or floating lanterns on the water terrace.',
    cuisine: 'Bespoke Multi-Course Degustation',
    hours: 'By Advance Reservation Only (24h notice recommended)',
    dressCode: 'Tailored',
    ambiance: 'Completely private architectural settings tailored to your party',
    image: 'https://images.unsplash.com/photo-1544025162-d76694265947?q=80&w=1600&auto=format&fit=crop',
    secondaryImage: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1600&auto=format&fit=crop',
    featuredDishes: [
      { name: 'The 7-Chapter Sensory Menu', description: 'A tailored culinary progression reflecting the seven architectural materials of Kairos', price: '₹14,000 / guest' },
      { name: 'Rare Vintage Sommelier Pairing', description: 'Cellar selections from Burgundy, Bordeaux, and emerging high-altitude vineyards', price: '₹8,500 / guest' },
      { name: 'Orchard Table Farm Showcase', description: 'Harvest-to-plate preparations cooked directly over live binchotan charcoal', price: '₹11,000 / guest' },
    ],
  },
];

export const SEED_AMENITIES: Amenity[] = [
  {
    id: 'amenity-pool',
    title: 'Heated Horizon Infinity Pool',
    category: 'Recreation',
    description: 'A 50-meter temperature-controlled black granite pool mirroring the sky, flanked by private shaded cabanas and heated daybeds.',
  },
  {
    id: 'amenity-spa',
    title: 'Ayurvedic & Longevity Spa',
    category: 'Wellness & Spa',
    description: 'Ten private treatment suites, cedar saunas, Himalayan salt relaxation rooms, and cold plunge hydrotherapy pools.',
  },
  {
    id: 'amenity-trails',
    title: 'Private Forest & Waterway Trails',
    category: 'Recreation',
    description: '4.5 miles of manicured walking and jogging trails through native biodiversity corridors and shaded bamboo groves.',
  },
  {
    id: 'amenity-fitness',
    title: 'Architectural Fitness Studio',
    category: 'Recreation',
    description: 'Technogym Artis equipment, private Pilates reformers, and floor-to-ceiling glass framing the botanical gardens.',
  },
  {
    id: 'amenity-cellar',
    title: 'Subterranean Wine Vault',
    category: 'Hospitality',
    description: 'Over 1,200 curated labels overseen by our Head Sommelier, with temperature-controlled private tasting vaults.',
  },
  {
    id: 'amenity-concierge',
    title: '24-Hour Private Concierge & Host',
    category: 'Hospitality',
    description: 'Dedicated estate host for every villa to orchestrate personalized itineraries, transfers, and in-suite requests.',
  },
  {
    id: 'amenity-helipad',
    title: 'Private Helipad & Chauffeur Fleet',
    category: 'Spaces',
    description: 'Direct on-site landing pad with Mercedes-Maybach fleet for seamless VIP transfers from Delhi International Airport.',
  },
  {
    id: 'amenity-farm',
    title: 'Organic Botanical Farm & Greenhouse',
    category: 'Spaces',
    description: 'Working zero-kilometer organic farm providing daily heirloom produce, honey, and fresh botanicals for all resort kitchens.',
  },
];

export const SEED_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    guestName: 'Aanya Mehta',
    location: 'Mumbai, India',
    rating: 5,
    review: 'The architecture alone is worth the journey. Everything feels deliberately quiet. Waking up to the morning fog over the reflection pool in the Garden Suite was the most restorative experience I have had in years.',
    roomStayed: 'Garden Suite',
    date: 'February 2026',
  },
  {
    id: 'rev-2',
    guestName: 'Jonathan Vance',
    location: 'London, United Kingdom',
    rating: 5,
    review: 'A masterclass in quiet luxury. No unnecessary gold or flashiness — just extraordinary proportions, travertine stone, and impeccable hospitality. The private dining in the orchard is truly unforgettable.',
    roomStayed: 'Signature Kairos Pavilion',
    date: 'January 2026',
  },
  {
    id: 'rev-3',
    guestName: 'Devansh & Priyal Singhania',
    location: 'New Delhi, India',
    rating: 5,
    review: 'We came for a weekend escape from the city and ended up extending for five days. The 360-degree views from the Horizon Villa and the Ayurvedic wellness rituals made us feel like we were thousands of miles away.',
    roomStayed: 'The Horizon Sky Villa',
    date: 'February 2026',
  },
  {
    id: 'rev-4',
    guestName: 'Elena Rostova',
    location: 'Zurich, Switzerland',
    rating: 5,
    review: 'Having stayed at luxury resorts across the globe, Kairos stands out for its profound architectural restraint and connection to nature. The staff anticipates every need without ever being intrusive.',
    roomStayed: 'Courtyard Residence',
    date: 'December 2025',
  },
];

export const SEED_BOOKINGS: Booking[] = [
  {
    id: 'book-sample-1',
    reservationCode: 'KAI-8821-A',
    roomId: 'signature-pavilion',
    roomName: 'Signature Kairos Pavilion',
    guestName: 'Rajesh Kapur',
    email: 'r.kapur@kapurholding.com',
    phone: '+91 98110 54321',
    specialRequests: 'Helipad landing clearance at 14:00. Allergen notice: shellfish.',
    checkIn: '2026-09-10',
    checkOut: '2026-09-14',
    adults: 4,
    children: 0,
    nights: 4,
    subtotal: 460000,
    tax: 82800,
    total: 542800,
    status: 'CONFIRMED',
    createdAt: '2026-08-15T10:30:00Z',
  },
  {
    id: 'book-sample-2',
    reservationCode: 'KAI-6743-B',
    roomId: 'ocean-villa',
    roomName: 'Horizon Ocean Villa',
    guestName: 'Sarah Jenkins',
    email: 'sarah.j@creativeguild.co.uk',
    phone: '+44 7700 900123',
    specialRequests: 'Celebrating wedding anniversary. Sunset champagne setup requested.',
    checkIn: '2026-09-18',
    checkOut: '2026-09-22',
    adults: 2,
    children: 0,
    nights: 4,
    subtotal: 180000,
    tax: 32400,
    total: 212400,
    status: 'CONFIRMED',
    createdAt: '2026-08-16T14:15:00Z',
  },
];
